#include <stdio.h>
#include <string.h>

#include "esp_console.h"
#include "esp_log.h"
#include "esp_serial_mux.h"
#include "esp_serial_mux_console.h"
#include "esp_serial_mux_log.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "sdkconfig.h"

static const char *TAG = "console_mux_demo";

static int help_command(int argc, char **argv)
{
    (void)argc;
    (void)argv;
    return esp_serial_mux_write_text(1,
                                     ESP_SERIAL_MUX_DIRECTION_OUTPUT,
                                     "available commands: help hello mux_manifest mux_hello mux_log\n",
                                     20);
}

static int hello_command(int argc, char **argv)
{
    (void)argc;
    (void)argv;
    return esp_serial_mux_write_text(1,
                                     ESP_SERIAL_MUX_DIRECTION_OUTPUT,
                                     "hello from esp_serial_mux console demo\n",
                                     20);
}

static int mux_manifest_command(int argc, char **argv)
{
    (void)argc;
    (void)argv;
    esp_err_t err = esp_serial_mux_emit_manifest(20);
    if (err == ESP_OK) {
        err = esp_serial_mux_write_text(1,
                                        ESP_SERIAL_MUX_DIRECTION_OUTPUT,
                                        "manifest emitted on channel 0\n",
                                        20);
    }
    return err;
}

static int mux_hello_command(int argc, char **argv)
{
    (void)argc;
    (void)argv;
    esp_err_t err = esp_serial_mux_write_text(3,
                                              ESP_SERIAL_MUX_DIRECTION_OUTPUT,
                                              "hello from mux telemetry channel\n",
                                              20);
    if (err == ESP_OK) {
        err = esp_serial_mux_write_text(1,
                                        ESP_SERIAL_MUX_DIRECTION_OUTPUT,
                                        "telemetry emitted on channel 3\n",
                                        20);
    }
    return err;
}

static int mux_log_command(int argc, char **argv)
{
    (void)argc;
    (void)argv;
    ESP_LOGI(TAG, "log generated by mux_log console command");
    return esp_serial_mux_write_text(1,
                                     ESP_SERIAL_MUX_DIRECTION_OUTPUT,
                                     "log emitted on channel 2\n",
                                     20);
}

static void register_demo_commands(void)
{
    const esp_console_cmd_t help_cmd = {
        .command = "help",
        .help = "List mux console demo commands",
        .hint = NULL,
        .func = help_command,
    };
    ESP_ERROR_CHECK(esp_console_cmd_register(&help_cmd));

    const esp_console_cmd_t hello_cmd = {
        .command = "hello",
        .help = "Print a normal console greeting",
        .hint = NULL,
        .func = hello_command,
    };
    ESP_ERROR_CHECK(esp_console_cmd_register(&hello_cmd));

    const esp_console_cmd_t mux_manifest_cmd = {
        .command = "mux_manifest",
        .help = "Emit mux manifest on the system channel",
        .hint = NULL,
        .func = mux_manifest_command,
    };
    ESP_ERROR_CHECK(esp_console_cmd_register(&mux_manifest_cmd));

    const esp_console_cmd_t mux_hello_cmd = {
        .command = "mux_hello",
        .help = "Emit a sample message on the mux telemetry channel",
        .hint = NULL,
        .func = mux_hello_command,
    };
    ESP_ERROR_CHECK(esp_console_cmd_register(&mux_hello_cmd));

    const esp_console_cmd_t mux_log_cmd = {
        .command = "mux_log",
        .help = "Emit a sample ESP log through the mux log adapter",
        .hint = NULL,
        .func = mux_log_command,
    };
    ESP_ERROR_CHECK(esp_console_cmd_register(&mux_log_cmd));
}

static void init_console_dispatcher(void)
{
    esp_console_config_t console_config = ESP_CONSOLE_CONFIG_DEFAULT();
    console_config.max_cmdline_length = 256;
    ESP_ERROR_CHECK(esp_console_init(&console_config));
}

static void init_mux(void)
{
    esp_serial_mux_config_t mux_config;
    esp_serial_mux_config_init(&mux_config);
    mux_config.max_payload_len = 512;
    mux_config.queue_depth = 32;
    ESP_ERROR_CHECK(esp_serial_mux_init(&mux_config));
    ESP_ERROR_CHECK(esp_serial_mux_start());

    const esp_serial_mux_channel_config_t system_channel = {
        .channel_id = ESP_SERIAL_MUX_CHANNEL_SYSTEM,
        .name = "system",
        .description = "System manifest and control messages",
        .directions = ESP_SERIAL_MUX_DIRECTION_OUTPUT,
        .default_payload_kind = ESP_SERIAL_MUX_PAYLOAD_KIND_CONTROL,
        .flush_policy = ESP_SERIAL_MUX_FLUSH_IMMEDIATE,
        .backpressure_policy = ESP_SERIAL_MUX_BACKPRESSURE_BLOCK_WITH_TIMEOUT,
    };
    ESP_ERROR_CHECK(esp_serial_mux_register_channel(&system_channel));

    esp_serial_mux_console_config_t console_config;
    esp_serial_mux_console_config_init(&console_config);
    console_config.channel_id = 1;
    console_config.mode = ESP_SERIAL_MUX_CONSOLE_MODE_LINE;
    ESP_ERROR_CHECK(esp_serial_mux_bind_console(&console_config));

    esp_serial_mux_log_config_t log_config;
    esp_serial_mux_log_config_init(&log_config);
    log_config.channel_id = 2;
    log_config.tee_to_previous = false;
    ESP_ERROR_CHECK(esp_serial_mux_bind_esp_log(&log_config));

    const esp_serial_mux_channel_config_t telemetry_channel = {
        .channel_id = 3,
        .name = "telemetry",
        .description = "Demo application text output",
        .directions = ESP_SERIAL_MUX_DIRECTION_OUTPUT,
        .default_payload_kind = ESP_SERIAL_MUX_PAYLOAD_KIND_TEXT,
        .flush_policy = ESP_SERIAL_MUX_FLUSH_PERIODIC,
        .backpressure_policy = ESP_SERIAL_MUX_BACKPRESSURE_DROP_OLDEST,
    };
    ESP_ERROR_CHECK(esp_serial_mux_register_channel(&telemetry_channel));

    ESP_ERROR_CHECK(esp_serial_mux_emit_manifest(20));
}

static void telemetry_task(void *arg)
{
    (void)arg;

    uint32_t counter = 0;
    while (true) {
        char message[96];
        snprintf(message, sizeof(message), "demo telemetry sample count=%lu\n", (unsigned long)counter++);
        (void)esp_serial_mux_write_text(3,
                                        ESP_SERIAL_MUX_DIRECTION_OUTPUT,
                                        message,
                                        20);
        ESP_LOGI(TAG, "demo periodic log count=%lu", (unsigned long)counter);
        vTaskDelay(pdMS_TO_TICKS(2000));
    }
}

void app_main(void)
{
    init_console_dispatcher();
    init_mux();
    register_demo_commands();

    ESP_ERROR_CHECK(xTaskCreate(telemetry_task,
                                "mux_telemetry_demo",
                                3072,
                                NULL,
                                4,
                                NULL) == pdPASS ? ESP_OK : ESP_ERR_NO_MEM);

    ESP_LOGI(TAG, "mux demo started");
    ESP_ERROR_CHECK(esp_serial_mux_write_text(3,
                                              ESP_SERIAL_MUX_DIRECTION_OUTPUT,
                                              "demo telemetry initial sample\n",
                                              20));

    while (true) {
        vTaskDelay(portMAX_DELAY);
    }
}
