#include <stdio.h>
#include <string.h>

#include "esp_console.h"
#include "esp_log.h"
#include "esp_serial_mux.h"
#include "esp_serial_mux_console.h"
#include "esp_serial_mux_log.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "sdkconfig.h"

static const char *TAG = "console_mux_demo";
static const char *PROMPT = "mux>";

static int hello_command(int argc, char **argv)
{
    (void)argc;
    (void)argv;
    printf("hello from esp_serial_mux console demo\n");
    return 0;
}

static int mux_manifest_command(int argc, char **argv)
{
    (void)argc;
    (void)argv;
    return esp_serial_mux_emit_manifest(20);
}

static int mux_hello_command(int argc, char **argv)
{
    (void)argc;
    (void)argv;
    return esp_serial_mux_write_text(3,
                                     ESP_SERIAL_MUX_DIRECTION_OUTPUT,
                                     "hello from mux telemetry channel\n",
                                     20);
}

static int mux_log_command(int argc, char **argv)
{
    (void)argc;
    (void)argv;
    ESP_LOGI(TAG, "log generated by mux_log console command");
    return 0;
}

static void register_demo_commands(void)
{
    const esp_console_cmd_t hello_cmd = {
        .command = "hello",
        .help = "Print a normal console greeting",
        .hint = NULL,
        .func = hello_command,
    };
    ESP_ERROR_CHECK(esp_console_cmd_register(&hello_cmd));

    const esp_console_cmd_t mux_manifest_cmd = {
        .command = "mux_manifest",
        .help = "Emit mux manifest on the system channel",
        .hint = NULL,
        .func = mux_manifest_command,
    };
    ESP_ERROR_CHECK(esp_console_cmd_register(&mux_manifest_cmd));

    const esp_console_cmd_t mux_hello_cmd = {
        .command = "mux_hello",
        .help = "Emit a sample message on the mux telemetry channel",
        .hint = NULL,
        .func = mux_hello_command,
    };
    ESP_ERROR_CHECK(esp_console_cmd_register(&mux_hello_cmd));

    const esp_console_cmd_t mux_log_cmd = {
        .command = "mux_log",
        .help = "Emit a sample ESP log through the mux log adapter",
        .hint = NULL,
        .func = mux_log_command,
    };
    ESP_ERROR_CHECK(esp_console_cmd_register(&mux_log_cmd));
}

static void start_console_repl(void)
{
    esp_console_repl_t *repl = NULL;
    esp_console_repl_config_t repl_config = ESP_CONSOLE_REPL_CONFIG_DEFAULT();
    repl_config.prompt = PROMPT;
    repl_config.max_cmdline_length = 256;

    register_demo_commands();

#if defined(CONFIG_ESP_CONSOLE_UART_DEFAULT) || defined(CONFIG_ESP_CONSOLE_UART_CUSTOM)
    esp_console_dev_uart_config_t hw_config = ESP_CONSOLE_DEV_UART_CONFIG_DEFAULT();
    ESP_ERROR_CHECK(esp_console_new_repl_uart(&hw_config, &repl_config, &repl));
#elif defined(CONFIG_ESP_CONSOLE_USB_CDC)
    esp_console_dev_usb_cdc_config_t hw_config = ESP_CONSOLE_DEV_CDC_CONFIG_DEFAULT();
    ESP_ERROR_CHECK(esp_console_new_repl_usb_cdc(&hw_config, &repl_config, &repl));
#elif defined(CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG)
    esp_console_dev_usb_serial_jtag_config_t hw_config = ESP_CONSOLE_DEV_USB_SERIAL_JTAG_CONFIG_DEFAULT();
    ESP_ERROR_CHECK(esp_console_new_repl_usb_serial_jtag(&hw_config, &repl_config, &repl));
#else
#error Unsupported console type
#endif

    ESP_ERROR_CHECK(esp_console_start_repl(repl));
}

static void init_mux(void)
{
    esp_serial_mux_config_t mux_config;
    esp_serial_mux_config_init(&mux_config);
    mux_config.max_payload_len = 512;
    mux_config.queue_depth = 32;
    ESP_ERROR_CHECK(esp_serial_mux_init(&mux_config));
    ESP_ERROR_CHECK(esp_serial_mux_start());

    const esp_serial_mux_channel_config_t system_channel = {
        .channel_id = ESP_SERIAL_MUX_CHANNEL_SYSTEM,
        .name = "system",
        .description = "System manifest and control messages",
        .directions = ESP_SERIAL_MUX_DIRECTION_OUTPUT,
        .default_payload_kind = ESP_SERIAL_MUX_PAYLOAD_KIND_CONTROL,
        .flush_policy = ESP_SERIAL_MUX_FLUSH_IMMEDIATE,
        .backpressure_policy = ESP_SERIAL_MUX_BACKPRESSURE_BLOCK_WITH_TIMEOUT,
    };
    ESP_ERROR_CHECK(esp_serial_mux_register_channel(&system_channel));

    esp_serial_mux_console_config_t console_config;
    esp_serial_mux_console_config_init(&console_config);
    console_config.channel_id = 1;
    console_config.mode = ESP_SERIAL_MUX_CONSOLE_MODE_LINE;
    ESP_ERROR_CHECK(esp_serial_mux_bind_console(&console_config));

    esp_serial_mux_log_config_t log_config;
    esp_serial_mux_log_config_init(&log_config);
    log_config.channel_id = 2;
    log_config.tee_to_previous = false;
    ESP_ERROR_CHECK(esp_serial_mux_bind_esp_log(&log_config));

    const esp_serial_mux_channel_config_t telemetry_channel = {
        .channel_id = 3,
        .name = "telemetry",
        .description = "Demo application text output",
        .directions = ESP_SERIAL_MUX_DIRECTION_OUTPUT,
        .default_payload_kind = ESP_SERIAL_MUX_PAYLOAD_KIND_TEXT,
        .flush_policy = ESP_SERIAL_MUX_FLUSH_PERIODIC,
        .backpressure_policy = ESP_SERIAL_MUX_BACKPRESSURE_DROP_OLDEST,
    };
    ESP_ERROR_CHECK(esp_serial_mux_register_channel(&telemetry_channel));

    ESP_ERROR_CHECK(esp_serial_mux_emit_manifest(20));
}

static void telemetry_task(void *arg)
{
    (void)arg;

    uint32_t counter = 0;
    while (true) {
        char message[96];
        snprintf(message, sizeof(message), "demo telemetry sample count=%lu\n", (unsigned long)counter++);
        (void)esp_serial_mux_write_text(3,
                                        ESP_SERIAL_MUX_DIRECTION_OUTPUT,
                                        message,
                                        20);
        ESP_LOGI(TAG, "demo periodic log count=%lu", (unsigned long)counter);
        vTaskDelay(pdMS_TO_TICKS(2000));
    }
}

void app_main(void)
{
    esp_console_register_help_command();
    start_console_repl();
    init_mux();

    ESP_ERROR_CHECK(xTaskCreate(telemetry_task,
                                "mux_telemetry_demo",
                                3072,
                                NULL,
                                4,
                                NULL) == pdPASS ? ESP_OK : ESP_ERR_NO_MEM);

    ESP_LOGI(TAG, "mux demo started");
    ESP_ERROR_CHECK(esp_serial_mux_write_text(3,
                                              ESP_SERIAL_MUX_DIRECTION_OUTPUT,
                                              "demo telemetry initial sample\n",
                                              20));

    while (true) {
        vTaskDelay(portMAX_DELAY);
    }
}
